// import 'package:intl/locale.dart';

// class L2n {
//   static final all = [
//     const Locale('en'),
//     const Locale('ar')
//   ];
// }
import 'package:get/get.dart';

class MyLocale implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "ar": {
      "CHOOSE_LANGUAGE": "اختر لغة",
      "CHANGE_LANGUAGE": "تغيير اللغة",
      "AR": "عربي",
      "EN": "English",
      //"1": "الصفحة الرئيسية"
      "Starting Text": "أفكار ومفاهيم",
      "Continue": "استمرار",
      "LOGIN": "تسجيل الدخول",
      "Google": "قوقل",
      "Facebook": "فيس بوك",
      "Email": "البريد الإلكتروني",
      "AS A GUEST": "كزائر",
      "User Name": "الإسم",
      "Password": "كلمة المرور",
      "SummerCuts": "تخفيضات الشتاء",
      "30% cuts": "تخفيضات تصل ل 30 % ",
      "Super Markets": "عملاونا",
      "Our Services": "خدماتنا",
      "Contacts": "للتواصل",
      "What's Up": "واتس أب",
      "Twitter": "تويتر",
      "Phone Call": "اتصال",
      "Nationality": "الجنسية",
      "City": "المدينة",
      "Has a car": "هل يوجد سيارة",
      "yes": "نعم",
      "No": "لا !!!",
      "welcome to Ideas and concepts group":
      "مرحبآ بك في مجموعة أفكار ومفاهيم ",
      "Manager": "المدير ",
      "Supervisor": "المشرف ",
      "Contact with us": "تواصل معنا عبر صفحاتنا",
      "Client Focused": "الإهتمام بالعميل",
      "Solution Driven": "قيادة الحلول",
      "Merchandising": "خدمات المنسقين",
      "Promotion & Delivery Services": "خدمات الدعم التسويقية ",
      "Southern": "المنطقة الشمالية",
      "Eastern": "المنطقة الغربية",
      "Northern": "المنطقة الجنوبية",
      "Western": "المنطقة شرقية",
      "Full name": "الإسم بالكامل",
      "Phone number": "رقم الهاتف",
      "National Id": "رقم الهوية ",
      "Birthday": "تاريخ الميلاد",
      "job starting day": "تاريخ بدء العمل",
      "Working Branch": "فرع العمل",
      "Upْload a Photo": "تحديد صورة",
      "Add a merchandiser": "إضافة منسق ",
      "Market": "المتجر",
      "Car Serial number": " رقم السيارة التلسلي",
      "Profile": "ملفي الشخصي",
      "Today's Tasks": "مهام اليوم",
      "log out": "تسجيل الخروج",
      "Add Task": "إضافة مهمة",
      "Delivery": "خدمة التوصيل",
      "Pricing": "تسعير وترتيب",
      "Inventory": "الجرد",
      "Other": "أخرى",
      "Before Ordering Photos": "قبل الترتيب",
      "Final Ordering Photos": "بعد الترتيب",
      "Delete a Merchandiser": " حذف منسق",
      "Tasks Details": "قم بتحديد بيانات المهمة",
      "P.O Number": "رقم الطلب :",
      "Invoice number": "رقم ضريبة القيمة المضافة",
      "Branch": "الفرع",
      "Merchandiser": "المنسق",
      "Add a Merchandiser": "إضافة منسق",
      "Cancel": "إلفاء",
      "Task Date": "تاريخ المهمة",
      "Welcome to tasks page": "مرحبآ بك في صفحة إضافة المهام",
      "Home": "الرئيسية",
      "Call Supervisor": " اتصال على المشرف",
      "Contact with Manager": "للتواصل مع المشرف",
      "First Market": "اقرب سوبرماركت",
      "Daily Tasks": "المهام اليومية ",
      "History": "سجل المهام",
      "New Tasks": "المهام الجديدة",
      "Capture Photo": "ترتيب الأرفف",
      "Image": "صورة",
      "RTV Section": "المرتجعات",
      "RTV Amount": "الكمية المرتجعة",
      "View": "عرض التفاصيل",
      "Planogram": "المخطط التفصيلي",
      "Availability": "المنتجات المتاحة",
      "Piece Tasks": "بالقطعة الواحدة",
      "Case Tasks": "بالمجموعة",
      "Full Case Tasks": "بالصندوق",
      "Take A photo": "أخذ صورة",
      "Deference Degree": "نسبة الإختلاف",
      "Expired": "منتهي الصلاحية",
      "Near Expired": "قرب انتهاء الصلاحية",
      "Damaged": "تالف",
      "Full Area": " المساحة الكلية",
      "ATTND": "وقت دخول النظام \n",
      "Job Information": "تفاصيل المهام",
      "Today Planned": "  مهام اليوم ",
      "Complete": "  ما تم اكماله",
      "The Rest": " المهام المتبقية  ",
      "Nearest OutLet!": 'اقرب فرع ',
      "Speak Up": "تواصلنا",
      "About": "عن",
      "No Image selected": " !! لم يتم اختيار صورة بعد",
      "next": "التالي",
      "Add": "إضافة ",
      "Main Planogram": " المخطط الأساسي",
      "Recent Planogram": " المخطط الحالي ",
      "Welcome": "مرحبآ @@",
      "Matching Degree": "نسبة التقارب",
      "Ok": "تم",
      "Compare": "مقارنة",
      "Save": "حفظ",
      "Take A Photo": "أخذ صورة",
      "Status": "الحالة",
      "Add To Photos Lists": "إضافة إلى القائمةٌ",
      "Working in": "يعمل الآن",
      "Task": "مهمة",
      "Share of Shelves": "التشاركية",
      "Update": "تحديث",
      "Car Details": "تفاصيل السيارة",
      "job Starting Day": "تاريخ بدء العمل",
      "Phone Number": "رقم الهاتف",
      "Full Name": "الإسم بالكامل",
      "All Tasks": "كل المهام",
      "Details": "التفاصيل",
      "Date": "التاريخ",
      "Time": "الوقت",
      "Location": "الموقع",
      "Made By": "تم بواسطة",
      "Back To Market": "عودة إلى المتجر",
      "Select a Merchandiser": "إختيار منسق",
      "Add To Task's List": "إضافة إلى قائمة المهام",
      "Select a Product": "اختيار منتج",
      "All Products": "كل المنتجات",
      "Any Merchandiser": "أي منسق",
      "Product": "المنتج",
      "Done Tasks": "المهام المكتملة",
      "Run Tasks": "المهام الحالية",
      //"New Tasks":"المهام الجديدة",
      "New Supermarket": "اختيار متجر جديد",
      "Go": "الذهاب",
      "Done": "مكتملة",
      "In Progress": "تعمل الآن",
      "To Do": "مهام جديدة",
      "Supervisors": "المشرفين",
      "Merchandisers": "منسقي الأرفف",
      // "Take Photos":
      "CAPTURE PHOTO has been add successfully": "تم إضافة الصور بنجاح",
      "Available": "متاح الآن",
      "Not Available": "غير متاح",
      //"The Rest": "المتبقي",
      "Get Shelve Photo": "اخذ صورة للشيلف",
      "Send to Manager": "إرسال للمشرف",
      "Success": "تم بنجاح",
      //"Share of Shelves": "التشاركية",
      "Before Adjustment": "قبل الترتيب",
      "After Adjustment": "بعد الترتيب",
      "Market Area": "مساحة الشركة",
      "System Attendance": "وقت الدخول",
      "Nearest Outlet": "أقرب فرع :",
      "Change Language": "تغيير اللغة",
      "Start": "بدء",
      "Merchandiser's lists": "قائمة المنسقين",
      "Branches": "الفروع",
      "Reports": "التقارير",
      "Tasks": " قائمة المهام",
      "Task Title": "نوع المهمة",
      // "Accept": "بدء المهمة",
      "Id": "رقم الهوية",
      // "My Profile": "ملفي الشخصي",
      "Change Branch": "تغيير الفرع",
      "Selected Product": "المنتج",
      "When you finish click ok": "عند الانتهاء قم بالضغط على الزر أدناه",
      "Go to Store Page": "اذهب الى المخزن",
      "On Shelf": "على الأرفف",
      "On Back Door": "على المخزن",
      "On Display": "على المعرض",
      "On Gandola": "على القندولة",
      "Amount": "الكمية المتوفرة",
      "m": "متر",
      "Shelf photo": "صورة  الرف",
      "Share Of Shelve": "مساحة الفرع",
      "Contact": "تواصل",
      "Shelf Ordering": "ترتيب الأرفف",
      "Rtv Report": "تقرير المرتجعات",
      "Rtv Reason": "سبب الإرجاع",
      "Product Name": "المنتج",
      "Done By": "قام به",
      "Create a Pdf": "إنشاء تقرير",
      "Report Created Day": "يوم انشاء التقرير",
      "Report Created Time": "ساعة انشاء التقرير",
      "Merchandisers List": "منسقي الأرفف",
      "Capture Photos Report": "تقرير صور الترتيب",
      "Report Created By": "تم انشاء التقرير بواسطة",
      "Photo's Ordering Report": "تقرير ترتيب الأرفف",
      "Title": "العنوان",
      "Images List": "عدد الصور",
      "Place": "مكان المنتج",
      "Available Amount": "الكمية المتاحة",
      "Share of Shelf": "مساحة الفرع",
      "Share of Shelves Report": "تقرير مشاركة الأرفف",
      "Pricing Report": "تقرير التسعير والترتيب",
      "Case": "الحالة",
      "Inventory Task Report": "تقرير الجرد",
      "Availability Task Report": "تقرير المنتجات المتاحة",
      "E-Mail Address": "البريد الإلكتروني",
      "Physical Address": "العنوان",
      "First Name": "الإسم الأول",
      "Second Name": "الإسم الثاني",
      "Last Name": "الإسم الآخير",
      "Task's List": "قائمة المهام",
      "Mr": "السيد",
      "Miss": "السيدة",
      "We Offer Job's for You": "تبحث عن وظيفة؟",

      "Network Error!!": "خطأ في الشبكة",
      "Login As Guest": "تم التدخول كضيف",
      "Job's Page": "صفحة الوظائف",
      "Job Request Form": "نموذج طلب توظيف",
      "Gender": "الجنس",
      "Select You Job": "قم بتحديد وظيفتك",
      "Hr Manager": "مدير موارد بشرية",
      "Promoter": " مروج منتجات",
      "Accountant": "محاسب",
      "Back": "رجوع",
      "Id Status": " حالة الهوية الوطنية",
      "Transferable": "قابلة للنقل",
      "Un Transferable": "غير قابلة للنقل",
      "Empty field": "هذا الحقل لا يمكن أن يكون فارغآ",
      "Value Must not Start With a Character": "هذا الحقل لا ينبغي أن يبدأ ب رمز",
      "Add Id Photo": "اختيار صورة الهوية",
      "Select Your Photo": "قم بإختيار صورتك",
      "From Camera": "التقاط صورة",
      "From Gallery": "من الاستوديو",
      "With Out Image": "بدون صورة",
      // "Id Case":"حاله ",
      "Id Number": "رقم الهوية الوطنية",
      "Select The Id Image": "اختيار صورة الهوية",
      "Enter Full Details": "قم بملء كل الحقول",
      "Next": "التالي",

      "Search": "بحث",
      "Start typing to search": "اكتب نص للبحث عنه",
      "Main Phone Number": "رقم الهاتف الأساسي",
      "Must Start With 5": "يجب آن يبدأ بالرقم 5",
      "Must Be 9 Digits": "يجب أن يكون ٩ خانات",
      "Second Phone Number": "رقم الهاتف الثاني",
      "Enter a valid E-mail": "قم بإدخال عنوان بريد الكتروني صالح",
      "Select Your Address": "قم بإختيار عنوانك",
      "Address": "العنوان",
      "Has A Car ??": "هل لديك سيارة ؟؟",
      "Yes": "نعم",
      "With Out Profile Image": "بدون صورة ملف شخصي",
      "Car Status": "حالة السيارة",
      "Not Selected Yet": "لم يتم الإختيار بعد",
      "Add Car Photo": "قم بإختيار صورة السيارة",
      "Car Image": "صورة السيارة",
      "Add Profile Photo": "قم بإختيار الملف الشخصي",
      "Profile Image": "صورة الملف الشخصي",
      "With Profile Image": "يوجد صورة ملف شخصي",
      "Your Request Under Process": "طلبك تحت المراجعة",
      "Confirm": "تأكيد",
      "Done Task's": "المهام المنتهية",
      "Run Task's": "المهام الحالية",
      "New Task's": "المهام الجديدة",

      "Before Ordering": "قبل الترتيب",
      "After Ordering": "بعد الترتيب",
      "View Location": "عرض الموقع",
      "Order By": "طُلب بواسطة",
      "Create Task": "ارسال المهمة",
      "On Shelves": "على الأرفف",
      "Select Your Task": "قم بإختيار المهمة",
      "All Places": "كل المواقع",
      "Select a Place": "إختيار موقع المنتج",
      "All Branches": "كل الفروع",
      "Rtv Task": "قسم المرتجعات",
      "Product Amount": "العدد الموجود",
      "Item": "قطعة",
      "Share Of Shelves Task": "مهمة مشاركة الأرفف",
      "Share Of Shelves": "مشاركة الأرفف",
      "Task Name": "نوع المهمة",
      "Availability Task": "مهمة المنتجات الموجودة",
      "Selected Display": "مكان عرض المنتج",
      "Inventory Task": "مهمة الجرد",
      "Pricing Task": "مهمة تسعير وترتيب",
      "All Markets": "كل المتاجر",
      "Expired Product's": "منتجات منتهية صلاحيتها",
      "Near Expired Product's": "منتجات ستنتهي صلاحيتها",
      "Damaged Product's": "المنتجات المحطمة",
      "Shelves Inventory": "جرد الأرفف",
      "Display Inventory": "جرد المعرض",
      "Gandola Inventory": "جرد القندولا",
      "Back Door Inventory": "جرد المخزن",
      "Shelves Availability": "المنتجات المتاحة على الأرفف",
      "Display Availability": "المنتجات المتاحة على المعرض",
      "Gandola Availability": "المنتجات المتاحة على القندولا",
      "Back Door Availability": "المنتجات المتاحة على المخزن",
      "Please pick a Image to upload": "قم بإختيار صورة لتحميلها",
      "No Result Yet": "لا توجد نتائج",
      "Excellent": "ترتيب متسق تمامآ",
      "Very Good": "ترتيب جيد جدآ",
      "Good": "ترتيب جيد",
      "Not Arranged": "غير مرتب",
      "Full Of Stock": "الرف ممتلئ",
      "Empty": "المساحة الفارغة",
      "Take A Picture": "لقطة كاميرا",
      "Take Another Picture": "لقطة كاميرا أخرى",
      "Review": "مراجعة",
      "Products List": "قائمة المنتجات",
      "One Product": "منتج واحد",
      "RTV Products": "المنتجات المرتجعة",
      "Return Quantity": "الكمية المرتجعة",
      "Category": "الفئة",
      "Upload": "تحميل",
      "Selected Place": "معرض المنتج",
      "Inventory Products": "منتجات الجرد",
      "Quantity": "الكمية",
      "Available Products": "المنتجات المتاحة",
      "Availability Products Status": "تفاصيل المنتجات المتاحة",
      "High Stock": "مخزون كبير",
      "Low Stock": "مخزون متدني",
      "View List": "عرض المنتجات",
      "Invent": "جرد",
      "Inventory With AI": "جرد بإستخدام الذكاء الإصطناعي ",
      "Normal Inventory": "جرد بدون الذكاء الإصطناعي",
      // "From Gallery": "من استوديو الصور",
      "Normal Availability": "بدون إستخدام الذكاء الإصطناعي",
      "Availability With AI": "بإستخدام الذكاء الإصطناعي",
      "Saturday": "السبت",
      "Monday": "الاثنين",
      "Wednesday": "الأربعاء",
      "Friday": "الجمعة",
      "Sunday": "الأحد",
      "Tuesday": "الثلاثاء",
      "Thursday": "الخميس",
      "Am": "مساء",
      "Schedule":"جدول الأيام",
      "LANGUAGE":"لغة التطبيق",
      "Dark Mode":"الوضع الداكن",
      "Logout":"تسجيل الخروج",
      "Un Completed":"غير المكتملة",
      "Finish Branch":"انهاء الزيارة",
      "Close??":"إغلاق؟؟",
      "You have uncompleted Tasks":"لديك مهام غير منتهية",
      "Close Branch":"إغلاق الفرع",
      "FullVisits":"الزيارات",
      "Offers":"عروض المنافسين",
      "All Categories":"كل الفئات",
      //"Add Product":"إضافة المنتج",
      "Using AI":"بالذكاء الإصطناعي",
      "Scan Barcode":"قارئ باركود",
      "Filter":"تصفية",
      "Send":"إرسال",
      "Read Data":"قراءة البيانات",
      "No Data":"لا يوجد بيانات",
      "Add to list":"إضافة للقائمة",
      "Inventory Section":"قسم الجرد",
      "Planogram Section":"قسم المخطط التفصيلي",
      "Availability Section":"قسم المنتجات المتاحة",
      "Shelf Area":"مساحة الرف",
      "Shelf Full Area":"المساحة الكلية",
      "Offers Section":"قسم العروض المنافسة",
      "Review Offers":"مراجعة العروض",
      "Add Product":"إضافة",
      "Shelf":"على الرف",
      "Price":"السعر",
      "Inventory Review":"مراجعة الجرد",
      "Calculate":"حساب المساحة",
      "Add Data To Last Ordering":"قم بإضافة صور",
      "Finish":"انهاء المهمة",
      "Empty Area":"المساحة الفارغة"
    },
    "en": {
      "CHOOSE_LANGUAGE": "Choose language",
      "AR": "عربي",
      "EN": "English",
      "Starting Text": "Ideas and Concepts",
      "Continue": "Continue",
      "LOGIN": "LOGIN",
      "Google": "Google",
      "Facebook": "Facebook",
      "Email": "Email",
      "Name": "Name",
      "Password": "Password",
      "Our Partners": "Our Partners",
      "Our Services": "Our Services",
      "Contacts": "Contacts",
      "What's Up": "What's Up",
      "Twitter": "Twitter",
      "Phone Call": "Phone Call",
      "Merchandiser Name": "Merchandiser Name",
      "Merchandiser details": "Enter Merchandiser Details ...",
      "Can't Be Empty": "This Field Can't Be Empty !!!",
      "Can't Be Less Than 10":
      "This field Can't e less than 10 Digit's !!!",
      "Merchandiser Working Details": "Enter Merchandiser Working Details",
      "Nationality": "Nationality",
      "City": "City",
      "Has a car": "Has a car ??",
      "Yes": "Yes",
      "No": "No",
      "welcome to Ideas and concepts group":
      "Welcome to Ideas and concepts group",
      "Manager": "Manager ",
      "Supervisor": "Supervisor",
      "Contact": "Contact",
      "web site developing": "Web site developing",
      "foundation Uniform": "Foundation Uniform",
      "CCTV": "CCTV",
      "Online Market": "Online Marketing",
      "Client Focused": "Client Focused",
      "Solution Driven": "Solution Driven",
      "Merchandising": "Merchandising",
      "Promotion & Delivery Services": "Promotion & Delivery Services",
      "Southern": "Southern ",
      "Eastern": "Eastern",
      "Northern": "Northern",
      "Western": "Western",
      "Full Name": "Full Name",
      "Phone Number": "Phone Number",
      "National Id": "National Id",
      "Birthday": "Birthday",
      "Job Starting Day": "Job Starting Day",
      "Working Branch": "Working Branch",
      "Upload a Photo": "Upload a Photo",
      "Add a Merchandiser": "Add a Merchandiser",
      "Market": "Market",
      "Car Serial number": "Car Serial number",
      "profile": "profile",
      "Today's Tasks": "Today's Tasks",
      "Log out": "Logout",
      "Add Task": "Add Task",
      "Delivery": "Delivery",
      "Pricing": "Pricing",
      "Inventory": "Inventory",
      "Other": "Other",
      "Delete Merchandiser": "Delete Merchandiser",
      "Tasks Details": "Tasks Details",
      "P.O Number": "P.O Number",
      "Invoice number": "Invoice number",
      "Merchandiser": "Merchandiser",
      "Add New Merchandiser": "Add New Merchandiser",
      "Cancel": "Cancel",
      "Welcome to tasks page": "Welcome to tasks page",
      "Home": "Home",
      "Daily Tasks": "Daily Tasks",
      "History": "History",
      "New Tasks": "New Tasks",
      "Capture Photo": "Shelves Ordering",
      "RTV Section": "RTV Section",
      "Planogram": "Planogram",
      "Availability": "Availability",
      // "Share 0f Shelf's": "Share 0f Shelf's",
      "Before Adjustment": "Before Adjustment",
      "After Adjustment": "After Adjustment",
      "Take A photo": "Take A photo",
      "Expired": "Expired",
      "Near Expired": "Near Expired",
      "Damaged": "Damaged",
      "Shelf Full Area": "Shelf Full Area",
      "Full Area": "Full Area",
      "Market Area": "Market Area",
      "System Attendance": "System Attendance!",
      "ATTND": "ATTND \n",
      "Job Information": "job Information!",
      "Today Planned": "Today's Planned :",
      "You Complete": "You Complete :",
      "The Rest": "The Rest : ",
      "About": "About!",
      "No Image selected": "No Image selected",
      "Next": "Next",
      "Details": "Details",
      "RTV Amount": "RTV Amount",
      "Add": "Add",
      "Main Planogram": "Main Planogram",
      "Recent Planogram": "Recent Planogram  ",
      "Welcome": "Welcome",
      "Matching degree": "Matching degree",
      "Ok": "Ok",
      "Compare": "Compare",
      "Save": "Save",
      "Available": "Available",
      "Not Available": "Not Available",
      "The rest": "The rest",
      "Get Shelve photo": "Get Shelve photo",
      "Success": "Success",
      "Skip": "Change Language",
      "Start": "Start",
      "Merchandiser's lists": "Merchandiser's lists",
      "Branches": "Branches",
      "Reports": "Reports",
      "Tasks": "Tasks",
      "Task Title": "Task Title",
      "Branch": "Branch",
      "Merchandiser Phone Number": "Merchandiser Phone",
      "Merchandiser id": "Merchandiser Id",
      //"task date": "task date",
      "Accept": "Accept",
      "Id": "Id",
      // "Profile": "Profile",
      "Change Branch": "Change Branch",
      "Selected Product": "Selected product",
      "Go to Store Page": "Go to Store Page",
      "Update": "update",
      "On Store": "On Store",
      "Amount": "Available Amount",
      "Rtv Report": "Rtv Report",
      "Rtv Reason": "Rtv Reason",
      "Product Name": "Product Name",
      "Done by": "Done by",
      "Create a Pdf": "Create a Pdf",
      "Report Created Day": "Report Created Day",
      "Report Created Time": "Report Created Time",
      "Merchandisers List": "Merchandisers List",

      "Task Date": "Task Date",
      "View": "View",
      "AS A GUEST": "AS A GUEST",
      "Before Ordering Photos": "Before Ordering Photos",
      "Final Ordering Photos": "Final Ordering Photos",
      "Create a pdf": "Create a pdf",
      "Capture Photos Report": "Capture Photos Report",
      "Report Created By": "Report Created By",
      "Call Supervisor": "Call Supervisor",
      "To Contact with Manager": "To Contact with Supervisor",
      "First Market": "First Market",
      "OSDS": "OSDS",
      "Piece Tasks": "Piece",
      "Case Tasks": "Case",
      "Full Case Tasks": "Full Case",
      //"Wellcome": "...........",
      "Deference Degree": ":نسبة الإختلاف",
      "Complete": "Complete",
      "Nearest OutLet": "Nearest OutLet",
      "Speak Up": "Speak Up",
      // "Next": "التالي",
      //"Details": " ...تفاصيل ",
      "Matching Degree": "Matching Degree:",
      "Take A Photo": "Take A Photo",
      "Status": "Status",
      "Add To Photos Lists": "Add To Photos Lists",
      "Working in": "Working in",
      "Task": "Task",
      "Share of Shelves": "Share of Shelves",
      "Car Details": "Car Details",
      "job Starting Day": "job Starting Day",
      "All Tasks": "All Tasks",
      "Date": "Date",
      "Time": "Time",
      "Location": "Location",
      "Made By": "Made By",
      "Back To Market": "Back To Marke",
      "Select a Merchandiser": "Select a Merchandiser",
      "On Shelve": "On Shelve",
      "Add To Task's List": "Add To Task's List",
      "Select a Product": "Select a Product",
      "All Products": "All Products",
      "Any Merchandiser": "Any Merchandiser",
      "Product": "Product",
      "Done Tasks": "Done Tasks",
      "Run Tasks": "Run Tasks",
      "Not Accepted": "Not Accepted",
      "New Supermarket": "New Supermarket",
      "Go": "Go",
      "Done": "Done",
      // "In Progress":"In Progress",
      // "Pending Tasks":"Pending Tasks",
      // "To Do":"To Do",
      "Supervisors": "Supervisors",
      "Merchandisers": "Merchandisers",
      "Photos Has Been Added Successfully":
      "Photos Has Been Added Successfully",
      "Get Shelve Photo": "Get Shelve Photo",
      "Send to Manager": "Send to Manager",
      "Shelve Full Area": "Shelve Full Area",
      "Nearest Outlet": "Nearest Outlet",
      "When You Finish Press Ok": "When You Finish Press Ok",
      "On Back Door": "On Back Door",
      "On Display": "On Display",
      "On Gandola": "On Gandola",
      "Image": "Image",
      "Am": "Am",
      "Share Of Shelve": "Share Of Shelve",
      "Shelve Ordering": "Shelve Ordering",
      "Photo's Ordering Report": "Photo's Ordering Report",
      "Saturday": "Saturday",
      "Monday": "Monday",
      "Wednesday": "Wednesday",
      "Friday": "Friday",
      "Sunday": "Sunday",
      "Tuesday": "Tuesday",
      "Thursday": "Thursday",

    }
  };
}
